export const LOGIN_STATUS_UNKNOWN = Symbol("LOGIN_STATUS_UNKNOWN");
export const LOGIN_STATUS_PENDING = Symbol("LOGIN_STATUS_PENDING");
export const LOGIN_STATUS_SUCCESS = Symbol("LOGIN_STATUS_SUCCESS");
export const LOGIN_STATUS_FAILURE = Symbol("LOGIN_STATUS_FAILURE");
